title: Nsenga Nigel
email: n.nigel@email.com
description: Personal portfolio of Nigel
baseurl: "/coursera-website_demo"
url: "https://nsenganigel.github.io"
twitter_username: jekyllrb
github_username: jekyll

# Build settings
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme